# Generated by Django 3.1 on 2020-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='사원번호')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('birth', models.DateField(verbose_name='생일')),
                ('department', models.CharField(max_length=30, verbose_name='부서')),
                ('rank', models.CharField(max_length=30, verbose_name='직급')),
            ],
            options={
                'verbose_name_plural': '직원',
            },
        ),
    ]
