# Generated by Django 3.1.1 on 2020-09-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('birth', models.DateField(verbose_name='생일')),
                ('photo', models.ImageField(upload_to='%d')),
                ('debut', models.DateField(verbose_name='데뷔')),
                ('site', models.CharField(max_length=100, verbose_name='사이트')),
                ('school', models.CharField(max_length=100, verbose_name='학력')),
                ('job', models.CharField(max_length=100, verbose_name='직업')),
            ],
            options={
                'verbose_name_plural': '나라',
            },
        ),
    ]
