# Generated by Django 3.1.1 on 2020-09-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0004_nara'),
    ]

    operations = [
        migrations.AddField(
            model_name='nara',
            name='today',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nara',
            name='today_f',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nara',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
