# Generated by Django 3.1.1 on 2020-09-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0005_auto_20200920_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nara',
            name='today_f',
            field=models.IntegerField(null=True),
        ),
    ]
